#!/usr/bin/env node
/**
 * Agent Daemon
 *
 * Runs alongside an agent (Claude Code, Cline, etc.) and:
 * 1. Polls the orchestrator for assigned tasks
 * 2. Notifies the agent when new tasks arrive
 * 3. Can auto-execute Claude Code commands
 *
 * Usage:
 *   npx tsx agent-daemon.ts --agent gemini-a --poll 60
 */

import * as fs from "fs";
import * as path from "path";
import { exec } from "child_process";

// ============================================================
// CONFIG
// ============================================================

const ORCHESTRATOR_URL = process.env.ORCHESTRATOR_URL || "http://localhost:3847";
const POLL_INTERVAL = parseInt(process.env.POLL_INTERVAL || "60") * 1000; // seconds -> ms
const AGENT_ID = process.argv.find((_arg, i) => process.argv[i - 1] === "--agent") || "unknown";
const INBOX_FILE = path.join(process.cwd(), `planning/agent-inbox/@${AGENT_ID}.md`);
const AUTO_EXECUTE = process.argv.includes("--auto");

console.log(`
Agent Daemon Starting
   Agent ID: ${AGENT_ID}
   Orchestrator: ${ORCHESTRATOR_URL}
   Poll Interval: ${POLL_INTERVAL / 1000}s
   Auto Execute: ${AUTO_EXECUTE}
   Inbox File: ${INBOX_FILE}
`);

// ============================================================
// TYPES
// ============================================================

interface AgentTask {
  id: string;
  agentId: string;
  taskId: string;
  sprint: string;
  status: string;
  description: string;
}

// ============================================================
// POLLING
// ============================================================

async function fetchMyTasks(): Promise<AgentTask[]> {
  try {
    const response = await fetch(`${ORCHESTRATOR_URL}/tasks/${AGENT_ID}`);
    const data = await response.json();
    return data.tasks || [];
  } catch (error) {
    console.error("Failed to fetch tasks:", error);
    return [];
  }
}

// ============================================================
// NOTIFICATION
// ============================================================

function notifyDesktop(title: string, message: string): void {
  // macOS notification
  if (process.platform === "darwin") {
    exec(`osascript -e 'display notification "${message}" with title "${title}"'`);
  }
  // Linux notification
  else if (process.platform === "linux") {
    exec(`notify-send "${title}" "${message}"`);
  }
  // Windows notification (PowerShell)
  else if (process.platform === "win32") {
    exec(`powershell -Command "New-BurntToastNotification -Text '${title}', '${message}'"`);
  }
}

function writeToInbox(tasks: AgentTask[]): void {
  const content = `# Inbox: @${AGENT_ID}
**Last Updated:** ${new Date().toISOString()}
**Pending Tasks:** ${tasks.length}

---

${tasks.map((t, i) => `
## Task ${i + 1}: ${t.taskId}
**Status:** ${t.status}
**Sprint:** ${t.sprint}
**Description:** ${t.description}
`).join("\n")}

---
*Auto-generated by agent-daemon*
`;

  fs.mkdirSync(path.dirname(INBOX_FILE), { recursive: true });
  fs.writeFileSync(INBOX_FILE, content);
}

// ============================================================
// AUTO-EXECUTION (experimental)
// ============================================================

function executeClaudeCode(task: AgentTask): void {
  if (!AUTO_EXECUTE) return;

  console.log(`Auto-executing task ${task.taskId}...`);

  // Create a prompt file for Claude Code
  const promptFile = path.join(process.cwd(), `.agent-prompt-${AGENT_ID}.md`);
  const prompt = `
# AUTO-ASSIGNED TASK: ${task.taskId}

**Sprint:** ${task.sprint}
**Description:** ${task.description}

## Instructions
1. Read WORKBOARD.md first
2. Claim this task
3. Implement following TDD
4. Report completion via:
   curl -X POST ${ORCHESTRATOR_URL}/report/complete \\
     -H "Content-Type: application/json" \\
     -d '{"agentId": "${AGENT_ID}", "taskId": "${task.taskId}", "filesChanged": [...], "checkpoint": "..."}'

## START NOW
`;

  fs.writeFileSync(promptFile, prompt);

  // This would need Claude Code CLI support for headless execution
  // For now, just notify
  console.log(`Prompt written to ${promptFile}`);
  notifyDesktop(`Task Assigned`, `${task.taskId}: ${task.description.slice(0, 50)}...`);
}

// ============================================================
// MAIN LOOP
// ============================================================

let lastTaskIds: string[] = [];

async function pollLoop(): Promise<void> {
  console.log(`\n[${new Date().toISOString()}] Polling...`);

  const tasks = await fetchMyTasks();
  const newTasks = tasks.filter(t => !lastTaskIds.includes(t.id));

  if (tasks.length > 0) {
    console.log(`Found ${tasks.length} pending tasks:`);
    tasks.forEach(t => console.log(`   - [${t.status}] ${t.taskId}: ${t.description.slice(0, 50)}...`));

    // Write to inbox file
    writeToInbox(tasks);

    // Notify on NEW tasks
    if (newTasks.length > 0) {
      console.log(`${newTasks.length} NEW tasks!`);
      notifyDesktop(
        `New Tasks for @${AGENT_ID}`,
        newTasks.map(t => t.taskId).join(", ")
      );

      // Auto-execute first new task (if enabled)
      if (AUTO_EXECUTE && newTasks[0]) {
        executeClaudeCode(newTasks[0]);
      }
    }
  } else {
    console.log(`No pending tasks`);
  }

  lastTaskIds = tasks.map(t => t.id);
}

// Start polling
pollLoop();
setInterval(pollLoop, POLL_INTERVAL);

console.log(`\nDaemon running. Press Ctrl+C to stop.\n`);
